#!/usr/bin/env python3
"""scene-status.py — the Scene Art rollout ledger (docs/SCENE_ART.md).

Scans every published entry and reports, per entry: does it have a real photo hero, and
which drawn Scene Art files exist (hero / snap1 / snap2). Writes docs/SCENE_STATUS.md — the
canonical tracker of what's been upgraded and what hasn't — and prints the priority work
queue: no-photo entries that still lack a drawn hero, most-recent first (the hero is the top
priority per the rollout plan).

Usage:
  python3 scripts/scene-status.py            # regenerate the ledger + print summary
  python3 scripts/scene-status.py --queue N  # just print the next N slugs to do (hero-less)
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "src", "content")
SCENES = os.path.join(ROOT, "src", "data", "scenes")
LEDGER = os.path.join(ROOT, "docs", "SCENE_STATUS.md")


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+?)\s*$", text, re.MULTILINE)
    if not m:
        return ""
    return m.group(1).strip().strip('"').strip("'")


def scan():
    rows = []
    for coll in ("attractions", "events"):
        for path in glob.glob(os.path.join(CONTENT, coll, "*.md")):
            slug = os.path.basename(path)[:-3]
            # Only the frontmatter block (between the first pair of --- fences).
            raw = open(path, encoding="utf-8").read()
            fm = raw.split("---", 2)[1] if raw.startswith("---") else raw
            hero = field(fm, "heroImage")
            approval = field(fm, "approval")
            if approval and approval != "published":
                continue
            rows.append(
                {
                    "slug": slug,
                    "coll": coll,
                    "title": field(fm, "title") or slug,
                    "created": field(fm, "createdAt"),
                    # heroImage may be a remote Commons URL or a locally-hosted path
                    # (e.g. a submitted illustration under /images/...) — either counts as
                    # a real hero image, not just http(s) URLs.
                    "photo": bool(hero),
                    "hero": os.path.exists(os.path.join(SCENES, f"{slug}.hero.svg")),
                    "snap1": os.path.exists(os.path.join(SCENES, f"{slug}.snap1.svg")),
                    "snap2": os.path.exists(os.path.join(SCENES, f"{slug}.snap2.svg")),
                }
            )
    rows.sort(key=lambda r: r["created"], reverse=True)
    return rows


def needs_hero(r):
    """A no-photo entry whose main image is still the emoji placeholder (top priority)."""
    return not r["photo"] and not r["hero"]


def write_ledger(rows):
    total = len(rows)
    photo = sum(r["photo"] for r in rows)
    nophoto = total - photo
    hero_done = sum(r["hero"] for r in rows)
    queue = [r for r in rows if needs_hero(r)]
    full = sum(r["hero"] and r["snap1"] and r["snap2"] for r in rows)

    def mark(b):
        return "✅" if b else "—"

    lines = [
        "# Scene Art rollout status",
        "",
        "> Generated by `scripts/scene-status.py` — do not hand-edit. Regenerate after adding scenes.",
        "",
        "The **hero** is the priority: any no-photo entry should get a drawn `hero` scene so its",
        "main image is real art, not the emoji placeholder. Snapshots (`snap1`/`snap2`) come after.",
        "",
        "## Summary",
        "",
        f"- Entries (published): **{total}**  ·  with real photo: **{photo}**  ·  no photo: **{nophoto}**",
        f"- Drawn hero present: **{hero_done}**  ·  full set (hero+snap1+snap2): **{full}**",
        f"- **Priority queue (no photo, no drawn hero): {len(queue)}** — listed first below.",
        "",
        "## Priority queue — no photo, still needs a drawn hero (most-recent first)",
        "",
        "| # | created | entry | slug |",
        "| --- | --- | --- | --- |",
    ]
    for i, r in enumerate(queue, 1):
        lines.append(f"| {i} | {r['created'][:10]} | {r['title']} | `{r['slug']}` |")
    lines += [
        "",
        "## Full ledger (most-recent first)",
        "",
        "| created | entry | slug | photo | hero | snap1 | snap2 |",
        "| --- | --- | --- | :-: | :-: | :-: | :-: |",
    ]
    for r in rows:
        lines.append(
            f"| {r['created'][:10]} | {r['title']} | `{r['slug']}` | "
            f"{mark(r['photo'])} | {mark(r['hero'])} | {mark(r['snap1'])} | {mark(r['snap2'])} |"
        )
    open(LEDGER, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    return total, photo, nophoto, hero_done, full, queue


def main():
    rows = scan()
    if "--queue" in sys.argv:
        n = int(sys.argv[sys.argv.index("--queue") + 1])
        for r in [x for x in rows if needs_hero(x)][:n]:
            print(f"{r['coll']}/{r['slug']}")
        return
    total, photo, nophoto, hero_done, full, queue = write_ledger(rows)
    print(f"ledger → {os.path.relpath(LEDGER, ROOT)}")
    print(f"  {total} published · {photo} photo · {nophoto} no-photo")
    print(f"  drawn hero: {hero_done} · full set: {full}")
    print(f"  priority queue (no photo, no hero): {len(queue)}")
    for r in queue[:10]:
        print(f"    - {r['created'][:10]}  {r['coll']}/{r['slug']}")
    if len(queue) > 10:
        print(f"    … and {len(queue) - 10} more")


if __name__ == "__main__":
    main()
